// ================================================================
// Trilingual content for the four priority feature landing pages.
// Each export is consumed by FeatureLandingPage as `content`.
// Shape per language:
//   eyebrow, h1Pre, h1Highlight, sub, highlights[], breakdownTitle,
//   sections[{title, body, bullets[]}], useCasesTitle, useCases[],
//   pricingTitle, pricingBody, faq[{q,a}], finalTitle, finalSub.
// ================================================================

export const efaturaContent = {
  TR: {
    eyebrow: "E-FATURA · GİB ENTEGRASYONU",
    h1Pre: "Türkiye'deki tüm e-Fatura ihtiyaçlarınız için",
    h1Highlight: "tek çözüm.",
    sub: "GİB onaylı altyapı, otomatik KDV hesaplama, e-Arşiv ve e-İrsaliye — hepsi tek panelde. Manuel takipten, formatlardan, hatalardan kurtulun.",
    highlightsTitle: "İşletmeniz için tasarlanmış e-Fatura",
    highlights: [
      { icon: "✅", title: "GİB Onaylı", body: "Doğrudan GİB sistemleriyle çalışır. Onaylar, RED'ler, iptaller anında işlenir." },
      { icon: "⚡", title: "Tek Tıkla Gönderim", body: "Fatura keser kesmez GİB'e iletilir. PDF, XML, UBL formatları otomatik üretilir." },
      { icon: "🧮", title: "Otomatik KDV", body: "%1, %10, %20 oranları otomatik. Tevkifat, ÖTV ve istisnalar dahil." },
      { icon: "📦", title: "Toplu İşlem", body: "Yüzlerce fatura tek seferde — şablonla, Excel'den içe aktarımla, API ile." },
    ],
    breakdownTitle: "Bir e-Faturayı baştan sona Zyrix yönetir",
    sections: [
      { title: "Müşteri ve ürün verisinden başlayın", body: "Müşteri bilgisi, ürün/hizmet kataloğu ve KDV oranları sistemde saklı. Yeni faturada her şey otomatik dolar.",
        bullets: ["Vergi numarası doğrulama", "MERSIS kontrolü", "Adres + alıcı tipinin GİB formatına çevrimi"] },
      { title: "Otomatik vergi hesabı", body: "KDV, tevkifat, stopaj ve istisnalar — manuel hesaplama gerekmez. Para birimi farklarında TCMB kuru otomatik çekilir.",
        bullets: ["Çoklu KDV oranı satırlarda", "Tevkifat kodları otomatik", "ÖTV ve özel matrah desteği"] },
      { title: "GİB'e gönderim ve takip", body: "Fatura kesilince GİB'e gönderilir, durumu canlı takip edilir. Onay, RED, iptal işlemleri anında bildirilir.",
        bullets: ["Onay/RED bildirim", "10 yıl arşiv otomatik", "İptal ve düzeltme işlemleri tek tıkla"] },
      { title: "e-Arşiv ve e-İrsaliye", body: "B2C için e-Arşiv, taşıma için e-İrsaliye — hepsi aynı sistemde. Tüm belgeler tek arşivde aranabilir.",
        bullets: ["e-Arşiv otomatik üretimi", "e-İrsaliye GİB entegrasyonu", "Tek arama ile 10 yıl geriye"] },
    ],
    useCasesTitle: "Kimlerin işine yarar?",
    useCases: [
      { icon: "🏪", title: "KOBİ'ler", body: "Aylık 10-1000 fatura kesen işletmeler için. Kurulum 10 dakika, mali müşavir entegrasyonu hazır." },
      { icon: "🏢", title: "E-ticaret", body: "Trendyol, Hepsiburada, Shopify entegrasyonları ile sipariş otomatik faturaya dönüşür." },
      { icon: "🚚", title: "Lojistik", body: "e-İrsaliye ile sevkiyat takibi otomatikleşir. GİB'e iletim, taşıma raporları, depodan teslimata izleme." },
    ],
    pricingTitle: "Tüm planlarda dahil",
    pricingBody: "Starter planında bile aylık 200 e-Faturaya kadar dahil. Daha fazlası için Growth ve Pro planları.",
    faq: [
      { q: "GİB sertifikası nasıl alınır?", a: "Süreci sizin için yönetiyoruz. Mali Mühür / e-İmza başvurusu ve entegrasyonu 1-3 iş günü içinde tamamlanır." },
      { q: "Mevcut faturalarımı taşıyabilir miyim?", a: "Evet. Excel, eski sistem dökümleri veya doğrudan API ile geçmiş faturaları içe aktarın. Geçiş sihirbazımız 1 saatte tamamlanır." },
      { q: "Mali müşavirim Zyrix'i kullanmasa olur mu?", a: "Olur. Mali müşavirinize PDF/XML çıktıları otomatik gönderilir. İsterseniz onu da hesabınıza davet edip ortak çalışma yapabilirsiniz." },
      { q: "İptal/düzeltme nasıl yapılır?", a: "Tek tıkla iptal başlatılır, düzeltme faturası otomatik kesilir. GİB onayları arka planda yürür." },
    ],
    finalTitle: "Bugün e-Fatura'ya geçin",
    finalSub: "Kurulum 10 dakika. İlk 14 gün ücretsiz. Mali müşavir entegrasyonu hazır.",
  },
  EN: {
    eyebrow: "E-INVOICE · GİB INTEGRATION",
    h1Pre: "Every Turkish e-Invoice need,",
    h1Highlight: "in one place.",
    sub: "GİB-approved infrastructure, automatic VAT, e-Archive and e-Waybill — all in one panel. No more manual chasing, formats, or mistakes.",
    highlightsTitle: "Built for your business",
    highlights: [
      { icon: "✅", title: "GİB Approved", body: "Direct integration with the GİB system. Approvals, rejections and cancels are processed live." },
      { icon: "⚡", title: "One-click delivery", body: "The moment you issue an invoice it goes to GİB. PDF, XML and UBL files are produced automatically." },
      { icon: "🧮", title: "Automatic VAT", body: "1%, 10%, 20% rates auto-applied. Withholding, SCT, exemptions all handled." },
      { icon: "📦", title: "Bulk operations", body: "Hundreds of invoices at once — templates, Excel import, API." },
    ],
    breakdownTitle: "Zyrix manages an e-Invoice end to end",
    sections: [
      { title: "Start from clean customer + product data", body: "Customer records, product/service catalogue and VAT rates live in the system, so each new invoice fills itself in.",
        bullets: ["Tax-ID validation", "MERSIS lookup", "Auto-mapping of address + buyer type to GİB format"] },
      { title: "Automatic tax math", body: "VAT, withholding, SCT and exemptions — no manual math. FX-rate against TCMB is fetched automatically when needed.",
        bullets: ["Multi-VAT lines per invoice", "Auto withholding codes", "SCT and special-base support"] },
      { title: "Submission and tracking", body: "When you issue, the invoice goes to GİB and its status is tracked live. Approvals, rejections and cancels notify you instantly.",
        bullets: ["Approval/rejection alerts", "10-year archive built in", "One-click cancel & correction"] },
      { title: "e-Archive and e-Waybill", body: "B2C invoices via e-Archive, shipments via e-Waybill — all in the same system. One archive, fully searchable.",
        bullets: ["Automatic e-Archive", "e-Waybill GİB integration", "10-year search across documents"] },
    ],
    useCasesTitle: "Who uses it",
    useCases: [
      { icon: "🏪", title: "SMBs", body: "Businesses issuing 10–1,000 invoices a month. 10-min setup, accountant integration ready." },
      { icon: "🏢", title: "E-commerce", body: "Trendyol, Hepsiburada and Shopify integrations turn orders into invoices automatically." },
      { icon: "🚚", title: "Logistics", body: "e-Waybill automates shipment paperwork. GİB submission, transport reports, depot-to-delivery tracking." },
    ],
    pricingTitle: "Included in every plan",
    pricingBody: "Even Starter includes up to 200 e-Invoices per month. Growth and Pro lift the cap further.",
    faq: [
      { q: "How do I get a GİB certificate?", a: "We handle the process. Financial seal / e-signature application and integration are completed within 1–3 business days." },
      { q: "Can I migrate my existing invoices?", a: "Yes — bring them in via Excel, an export from your old system, or our API. The migration wizard usually finishes in under an hour." },
      { q: "What if my accountant doesn't use Zyrix?", a: "Fine. PDF/XML exports go to your accountant automatically — and you can invite them to collaborate inside your account if you'd like." },
      { q: "How do cancellations and corrections work?", a: "One-click cancel triggers a corrective invoice automatically. GİB approvals run in the background." },
    ],
    finalTitle: "Switch to e-Invoice today",
    finalSub: "10-minute setup. First 14 days free. Accountant integration ready.",
  },
  AR: {
    eyebrow: "الفاتورة الإلكترونية · تكامل GİB",
    h1Pre: "كل احتياجاتك للفوترة الإلكترونية في تركيا",
    h1Highlight: "في حل واحد.",
    sub: "بنية معتمدة من GİB، حساب VAT تلقائي، e-Arşiv وe-İrsaliye — كلّها في لوحة واحدة. وداعاً للمتابعة اليدوية والصيغ والأخطاء.",
    highlightsTitle: "مصممة لعملك",
    highlights: [
      { icon: "✅", title: "معتمد من GİB", body: "تكامل مباشر مع GİB. الموافقات والرفض والإلغاء تُعالج فوراً." },
      { icon: "⚡", title: "إرسال بنقرة واحدة", body: "بمجرد إصدار الفاتورة تذهب إلى GİB. ملفات PDF وXML وUBL تُنتَج آلياً." },
      { icon: "🧮", title: "ضريبة تلقائية", body: "نسب 1% و10% و20% تُطبَّق تلقائياً. خصومات وضرائب خاصة وإعفاءات مدمجة." },
      { icon: "📦", title: "عمليات جماعية", body: "مئات الفواتير دفعة واحدة — قوالب، استيراد Excel، أو API." },
    ],
    breakdownTitle: "Zyrix يدير الفاتورة من البداية للنهاية",
    sections: [
      { title: "ابدأ من بيانات العميل والمنتج", body: "بيانات العملاء وكتالوج المنتجات/الخدمات ومعدلات الضريبة محفوظة، فكل فاتورة جديدة تكتمل تلقائياً.",
        bullets: ["تحقق من الرقم الضريبي", "بحث MERSIS", "ربط آلي للعنوان ونوع المشتري بصيغة GİB"] },
      { title: "حساب ضريبي تلقائي", body: "VAT، خصومات، ضرائب خاصة، وإعفاءات — بدون حساب يدوي. سعر TCMB يُحضر تلقائياً عند الحاجة.",
        bullets: ["نسب VAT متعددة في الفاتورة", "أكواد خصم تلقائية", "دعم SCT وقواعد خاصة"] },
      { title: "الإرسال والمتابعة", body: "عند الإصدار تذهب الفاتورة إلى GİB ويُتابع وضعها مباشرة. الموافقات والرفض والإلغاء تصلك فوراً.",
        bullets: ["تنبيهات قبول/رفض", "أرشيف 10 سنوات مدمج", "إلغاء وتصحيح بنقرة واحدة"] },
      { title: "e-Arşiv وe-İrsaliye", body: "فواتير B2C عبر e-Arşiv، الشحنات عبر e-İrsaliye — كلّها في نفس النظام. أرشيف واحد قابل للبحث.",
        bullets: ["إنتاج e-Arşiv آلي", "تكامل e-İrsaliye مع GİB", "بحث في 10 سنوات عبر كل المستندات"] },
    ],
    useCasesTitle: "لمن هذه الميزة؟",
    useCases: [
      { icon: "🏪", title: "الشركات الصغيرة والمتوسطة", body: "للشركات التي تُصدر 10–1000 فاتورة شهرياً. إعداد في 10 دقائق وتكامل المحاسب جاهز." },
      { icon: "🏢", title: "التجارة الإلكترونية", body: "تكاملات Trendyol وHepsiburada وShopify تحوّل الطلبات إلى فواتير تلقائياً." },
      { icon: "🚚", title: "الخدمات اللوجستية", body: "e-İrsaliye يؤتمت أوراق الشحن. إرسال GİB، تقارير النقل، تتبع من المستودع للتسليم." },
    ],
    pricingTitle: "مشمولة في كل الباقات",
    pricingBody: "حتى باقة Starter تتضمن 200 فاتورة شهرياً. Growth وPro يرفعان الحد." ,
    faq: [
      { q: "كيف أحصل على شهادة GİB؟", a: "نحن نتولى العملية. تقديم الختم المالي / التوقيع الإلكتروني والتكامل خلال 1–3 أيام عمل." },
      { q: "هل يمكنني نقل فواتيري الحالية؟", a: "نعم — استورد عبر Excel أو من نظامك القديم أو عبر API. معالج الترحيل ينتهي عادةً في أقل من ساعة." },
      { q: "ماذا لو كان محاسبي لا يستخدم Zyrix؟", a: "لا مشكلة. تذهب صادرات PDF/XML للمحاسب تلقائياً، ويمكنك دعوته للتعاون داخل حسابك." },
      { q: "كيف يعمل الإلغاء والتصحيح؟", a: "إلغاء بنقرة واحدة يولد فاتورة تصحيحية تلقائياً. موافقات GİB تعمل في الخلفية." },
    ],
    finalTitle: "حوّل إلى الفاتورة الإلكترونية اليوم",
    finalSub: "إعداد في 10 دقائق. أول 14 يوماً مجاناً. تكامل المحاسب جاهز.",
  },
};

export const crmContent = {
  TR: {
    eyebrow: "CRM · MÜŞTERİ YÖNETİMİ",
    h1Pre: "Müşterilerinizi tanıyın,",
    h1Highlight: "büyütün, kaybetmeyin.",
    sub: "Müşteri 360° görünümü, görsel satış pipeline'ı, churn tahmini ve otomatik takip — tek sistem içinde.",
    highlightsTitle: "İlişki kurma, sezgilerle değil verilerle",
    highlights: [
      { icon: "👥", title: "360° Müşteri", body: "Tüm faturalar, ödemeler, e-postalar ve aramalar tek profilde." },
      { icon: "📊", title: "Görsel Pipeline", body: "Lead → görüşme → teklif → kazanım. Sürükle-bırak takip." },
      { icon: "🧬", title: "Müşteri DNA'sı", body: "Davranış skorları: ödeme alışkanlığı, sipariş hacmi, kayıp riski." },
      { icon: "🔮", title: "Churn Tahmini", body: "Riskli müşterileri kaybetmeden önce işaret eder." },
    ],
    breakdownTitle: "İlk değil son söz Zyrix'in",
    sections: [
      { title: "Tüm temas noktaları tek yerde", body: "E-postalar, WhatsApp mesajları, faturalar, ödemeler ve notlar aynı zaman çizelgesinde toplanır.",
        bullets: ["Outlook/Gmail entegrasyonu", "WhatsApp Business mesaj geçmişi", "Otomatik fatura zincirleme"] },
      { title: "Pipeline yönetimi", body: "Satış aşamalarını sürükle-bırak, fırsatlara değer ata, kazanma olasılığı AI ile hesaplansın.",
        bullets: ["Özelleştirilebilir aşamalar", "AI kazanma skorları", "Tahmini ciroyu canlı görün"] },
      { title: "Müşteri segmentasyonu", body: "Sektör, hacim, ödeme alışkanlığı, coğrafya — istediğiniz kombinasyonla segment oluşturun.",
        bullets: ["Dinamik segmentler", "Otomatik etiketleme", "Pazarlama kampanyalarına bağla"] },
      { title: "Churn tahmini ve aksiyonlar", body: "Risk skorları yükselen müşteriler önceliklendirilir. Otomatik kurtarma kampanyaları başlatılır.",
        bullets: ["Risk skoru zaman çizelgesi", "Otomatik kurtarma e-postası", "Hesap yöneticisine alarm"] },
    ],
    useCasesTitle: "Kimlerin işine yarar?",
    useCases: [
      { icon: "💼", title: "Satış ekipleri", body: "Pipeline yönetimi, hedef takibi ve performans raporları tek panelde." },
      { icon: "🎯", title: "Pazarlama", body: "Segment bazlı kampanyalar, kurtarma akışları ve ROI analizleri." },
      { icon: "👨‍💼", title: "Hesap yöneticileri", body: "Müşteri sağlığını gerçek zamanlı izleyin, risk altındakilere zamanında müdahale edin." },
    ],
    pricingTitle: "Growth ve Pro planlarında dahil",
    pricingBody: "Starter planında temel CRM, Growth'ta pipeline + segmentasyon, Pro'da churn AI ve otomasyonlar.",
    faq: [
      { q: "Mevcut CRM verilerimi taşıyabilir miyim?", a: "Evet. HubSpot, Pipedrive, Salesforce, Excel veya CSV import desteği var. 1 saatte tamamlanır." },
      { q: "Pipeline aşamalarını özelleştirebilir miyim?", a: "Tabii. İstediğiniz kadar aşama ekleyin, isimlendirin ve renklendirin. Her ekibin kendi pipeline'ı olabilir." },
      { q: "Churn tahmini nasıl çalışır?", a: "Geçmiş 12 ayın davranış verisini AI işler: ödeme gecikmeleri, sipariş hacmi düşüşü, etkileşim azalması. %85+ doğrulukla risk skoru üretir." },
      { q: "WhatsApp Business entegrasyonu var mı?", a: "Evet. Müşteriyle WhatsApp yazışmaları otomatik profil zaman çizelgesine eklenir." },
    ],
    finalTitle: "Müşterilerinizi gerçekten tanımaya başlayın",
    finalSub: "İlk 14 gün ücretsiz. Kurulum sihirbazı 10 dakikada CRM'i hazır eder.",
  },
  EN: {
    eyebrow: "CRM · CUSTOMER MANAGEMENT",
    h1Pre: "Know your customers,",
    h1Highlight: "grow them, keep them.",
    sub: "360° customer view, visual sales pipeline, churn forecasting and automated follow-ups — one system.",
    highlightsTitle: "Relationships built on data, not guesses",
    highlights: [
      { icon: "👥", title: "360° Customer", body: "Every invoice, payment, email and call in one profile." },
      { icon: "📊", title: "Visual pipeline", body: "Lead → conversation → proposal → won. Drag-and-drop tracking." },
      { icon: "🧬", title: "Customer DNA", body: "Behaviour scores: payment habit, order volume, churn risk." },
      { icon: "🔮", title: "Churn forecast", body: "Flags at-risk customers before they leave." },
    ],
    breakdownTitle: "Zyrix has the last word, not the first",
    sections: [
      { title: "Every touchpoint in one place", body: "Emails, WhatsApp messages, invoices, payments and notes land on the same timeline.",
        bullets: ["Outlook/Gmail sync", "WhatsApp Business history", "Automatic invoice threading"] },
      { title: "Pipeline management", body: "Drag-and-drop stages, attach value to opportunities, and let AI score win likelihood.",
        bullets: ["Customisable stages", "AI win scores", "Live revenue forecast"] },
      { title: "Segmentation", body: "Industry, volume, payment habit, geography — combine any way you like.",
        bullets: ["Dynamic segments", "Auto-tagging", "Plug into marketing campaigns"] },
      { title: "Churn forecast & action", body: "Customers whose risk score rises are prioritised, and recovery flows fire automatically.",
        bullets: ["Risk score over time", "Auto recovery email", "Account-manager alerts"] },
    ],
    useCasesTitle: "Who uses it",
    useCases: [
      { icon: "💼", title: "Sales teams", body: "Pipeline, quotas and performance reports in one panel." },
      { icon: "🎯", title: "Marketing", body: "Segment-based campaigns, recovery flows and ROI analytics." },
      { icon: "👨‍💼", title: "Account managers", body: "Watch customer health in real time and step in before churn." },
    ],
    pricingTitle: "Included in Growth and Pro",
    pricingBody: "Starter ships with the basics; Growth adds pipeline + segmentation; Pro unlocks churn AI and automations.",
    faq: [
      { q: "Can I import data from my current CRM?", a: "Yes — HubSpot, Pipedrive, Salesforce, Excel and CSV imports are supported. Most teams finish in under an hour." },
      { q: "Can I customise pipeline stages?", a: "Of course. Add as many stages as you want, name and colour them. Each team can have its own pipeline." },
      { q: "How does churn forecasting work?", a: "AI processes the last 12 months of behaviour: late payments, volume drops, engagement declines — and produces a risk score that's typically 85%+ accurate." },
      { q: "Is there WhatsApp Business integration?", a: "Yes. WhatsApp threads with a customer attach automatically to their profile timeline." },
    ],
    finalTitle: "Start actually knowing your customers",
    finalSub: "First 14 days free. Setup wizard has CRM ready in 10 minutes.",
  },
  AR: {
    eyebrow: "CRM · إدارة العملاء",
    h1Pre: "اعرف عملاءك،",
    h1Highlight: "ربّيهم، ولا تخسرهم.",
    sub: "رؤية 360° للعميل، خط مبيعات بصري، توقع الانسحاب، ومتابعات مؤتمتة — نظام واحد.",
    highlightsTitle: "علاقات مبنية على البيانات، لا التخمين",
    highlights: [
      { icon: "👥", title: "عميل 360°", body: "كل فاتورة ودفع وبريد ومكالمة في ملف واحد." },
      { icon: "📊", title: "خط مبيعات بصري", body: "محتمل ← محادثة ← عرض ← فوز. سحب وإفلات." },
      { icon: "🧬", title: "DNA العميل", body: "درجات السلوك: عادة الدفع، حجم الطلب، خطر الفقد." },
      { icon: "🔮", title: "توقع الفقد", body: "يحدد العملاء المعرضين للفقد قبل رحيلهم." },
    ],
    breakdownTitle: "Zyrix يقول الكلمة الأخيرة، لا الأولى",
    sections: [
      { title: "كل نقاط التواصل في مكان واحد", body: "البريد ومحادثات WhatsApp والفواتير والمدفوعات والملاحظات على نفس الجدول الزمني.",
        bullets: ["تكامل Outlook/Gmail", "سجل WhatsApp Business", "ربط آلي للفواتير"] },
      { title: "إدارة خط المبيعات", body: "مراحل بسحب وإفلات، قيمة لكل فرصة، ودرجة فوز تُحسبها AI.",
        bullets: ["مراحل قابلة للتخصيص", "درجات فوز AI", "توقع إيرادات مباشر"] },
      { title: "تقسيم العملاء", body: "القطاع، الحجم، عادة الدفع، الجغرافيا — اجمع أي مزيج تريد.",
        bullets: ["شرائح ديناميكية", "وسم تلقائي", "ربط بحملات التسويق"] },
      { title: "توقع الفقد والإجراء", body: "تُمنح الأولوية للعملاء الذين ترتفع درجة خطرهم، وتنطلق سلاسل الاستعادة آلياً.",
        bullets: ["درجة الخطر زمنياً", "بريد استعادة آلي", "تنبيه مدير الحساب"] },
    ],
    useCasesTitle: "لمن هذه الميزة؟",
    useCases: [
      { icon: "💼", title: "فرق المبيعات", body: "خط المبيعات والأهداف والأداء في لوحة واحدة." },
      { icon: "🎯", title: "التسويق", body: "حملات بالشرائح، سلاسل استعادة، وتحليلات ROI." },
      { icon: "👨‍💼", title: "مدراء الحسابات", body: "راقب صحة العميل لحظياً وتدخّل قبل الفقد." },
    ],
    pricingTitle: "مشمولة في باقتي Growth وPro",
    pricingBody: "Starter يضم الأساسيات، Growth يضيف خط المبيعات والشرائح، Pro يفتح AI الفقد والأتمتة.",
    faq: [
      { q: "هل أستطيع استيراد بياناتي من CRM حالي؟", a: "نعم — HubSpot وPipedrive وSalesforce وExcel وCSV مدعومة. تنتهي معظم الفرق في أقل من ساعة." },
      { q: "هل أستطيع تخصيص مراحل خط المبيعات؟", a: "بالتأكيد. أضف ما تشاء من المراحل بأسماء وألوان. كل فريق يمكن أن يكون له خطه الخاص." },
      { q: "كيف يعمل توقع الفقد؟", a: "AI يعالج 12 شهراً من السلوك: تأخر الدفع، انخفاض الحجم، تراجع التفاعل — ويُخرج درجة خطر بدقة 85%+." },
      { q: "هل يوجد تكامل WhatsApp Business؟", a: "نعم. محادثات WhatsApp مع العميل تُضاف تلقائياً لجدوله الزمني." },
    ],
    finalTitle: "ابدأ بمعرفة عملائك حقاً",
    finalSub: "أول 14 يوماً مجاناً. معالج الإعداد يجهّز CRM في 10 دقائق.",
  },
};

export const aiContent = {
  TR: {
    eyebrow: "AI · YAPAY ZEKA ASİSTAN",
    h1Pre: "Yapay zeka ile finansal CFO'nuz",
    h1Highlight: "cebinizde.",
    sub: "Tax Autopilot, Death Predictor, Co-Founder Mode, Voice-to-Invoice ve banka mutabakatı — Gemini destekli AI tek panelinizde.",
    highlightsTitle: "Bir CFO'nun yapacağı işi AI yapsın",
    highlights: [
      { icon: "🧾", title: "Tax Autopilot", body: "KDV beyanlarını AI hazırlar, mali müşaviriniz onaylar." },
      { icon: "💀", title: "Death Predictor", body: "İşletmenin nakit ölüm tarihini önceden hesaplar." },
      { icon: "🤝", title: "Co-Founder Mode", body: "Kararlarınızı tartıştığınız sanal kurucu ortağınız." },
      { icon: "🎤", title: "Voice-to-Invoice", body: "Sesle fatura kesin: 'Ahmet'e 12.500 TL fatura kes' deyin, gerisini AI halletsin." },
    ],
    breakdownTitle: "İçeride neler var?",
    sections: [
      { title: "Tax Autopilot", body: "KDV-1, KDV-2, muhtasar beyannamelerini AI hazırlar. Mali müşaviriniz tek tıkla onaylar.",
        bullets: ["KDV-1, KDV-2 otomatik hazırlama", "Muhtasar beyanname taslağı", "GİB e-Beyanname'ye gönderim"] },
      { title: "Death Predictor", body: "Mevcut nakit, gelen ve giden ödemeler analiz edilir; nakit tükenme tarihi hesaplanır. Aksiyon önerileri sunulur.",
        bullets: ["30/60/90 gün nakit projeksiyonu", "Risk faktörleri ve etkileri", "Nakit kurtarma aksiyon planı"] },
      { title: "Co-Founder Mode", body: "İşletme kararlarınızı AI ile tartışın: fiyat indirimi, yeni iş kolu, personel alımı. Veri-temelli ikinci görüş.",
        bullets: ["Senaryo simülasyonu", "Sektör karşılaştırması", "Nakit etkili karar analizi"] },
      { title: "Voice-to-Invoice + Banka Mutabakatı", body: "Sesle fatura komutları, banka hareketlerini AI eşler. Mutabakat saatler değil dakikalar sürer.",
        bullets: ["Türkçe sesli komut", "Banka hareketleri otomatik eşleme", "%95+ mutabakat doğruluğu"] },
    ],
    useCasesTitle: "Kimlerin işine yarar?",
    useCases: [
      { icon: "👤", title: "Solo girişimciler", body: "Mali müşavir + CFO + asistan — hepsi AI içinde. Tek başınıza yönetebilirsiniz." },
      { icon: "📈", title: "Büyüyen KOBİ'ler", body: "Karar süreçlerinizde veri-temelli ikinci görüş. Hızlı büyürken kontrolü kaybetmeyin." },
      { icon: "💼", title: "Finans yöneticileri", body: "Rutin işleri AI'ya bırakın, stratejik kararlara odaklanın." },
    ],
    pricingTitle: "Pro planında dahil",
    pricingBody: "Starter ve Growth planlarında temel AI sorgulama, Pro planda tüm AI motorları (Tax Autopilot, Death Predictor, Co-Founder).",
    faq: [
      { q: "AI verilerime erişebilir mi?", a: "Sadece sizin onayınızla. Veriler şifreli kalır, OpenAI/Google'a kişisel bilgi gitmez. KVKK ve GDPR uyumlu." },
      { q: "Türkçe doğal dil sorgular ne kadar iyi anlıyor?", a: "Gemini 2.0 ile Türkçe destek native seviyede. Mali terminoloji ve sektör jargonu için özel olarak ince-ayar yapıldı." },
      { q: "Tax Autopilot mali müşavir yerine geçer mi?", a: "Hayır, mali müşavirinizi destekler. Hazırlama işi AI'da, onay ve sorumluluk mali müşavirinizdedir." },
      { q: "Voice-to-Invoice hangi cihazlarda çalışır?", a: "iOS, Android, Mac, Windows. Mobil uygulamada her zaman aktif, web'de mikrofon izniyle." },
    ],
    finalTitle: "AI'dan korkmayın — kullanın",
    finalSub: "İlk 14 gün ücretsiz, kredi kartı yok. AI rehberi her adımda yanınızda.",
  },
  EN: {
    eyebrow: "AI · ALWAYS-ON ASSISTANT",
    h1Pre: "Your AI CFO,",
    h1Highlight: "in your pocket.",
    sub: "Tax Autopilot, Death Predictor, Co-Founder Mode, Voice-to-Invoice and bank reconciliation — Gemini-powered, in one panel.",
    highlightsTitle: "Let AI do the CFO work",
    highlights: [
      { icon: "🧾", title: "Tax Autopilot", body: "AI drafts your VAT returns; your accountant approves." },
      { icon: "💀", title: "Death Predictor", body: "Calculates your cash 'death date' before it sneaks up." },
      { icon: "🤝", title: "Co-Founder Mode", body: "A virtual co-founder you can talk decisions through with." },
      { icon: "🎤", title: "Voice-to-Invoice", body: "Say 'invoice Ahmet 12,500 TL', AI handles the rest." },
    ],
    breakdownTitle: "What's inside",
    sections: [
      { title: "Tax Autopilot", body: "AI drafts VAT-1, VAT-2 and withholding returns. Your accountant approves them with one click.",
        bullets: ["Auto VAT-1 and VAT-2 drafts", "Withholding return template", "Direct submission to GİB e-Declaration"] },
      { title: "Death Predictor", body: "Current cash plus inflows and outflows are analysed; a cash-runout date is calculated, with action recommendations.",
        bullets: ["30/60/90-day projection", "Risk factors and impact", "Cash-recovery action plan"] },
      { title: "Co-Founder Mode", body: "Talk decisions through with AI: price changes, new lines of business, hiring. A data-driven second opinion.",
        bullets: ["Scenario simulation", "Industry benchmarking", "Cash-impact decision analysis"] },
      { title: "Voice-to-Invoice + Bank Reconciliation", body: "Voice commands for invoicing; AI matches bank transactions. Reconciliation that takes minutes, not hours.",
        bullets: ["Native Turkish voice commands", "Auto-matched bank transactions", "95%+ reconciliation accuracy"] },
    ],
    useCasesTitle: "Who uses it",
    useCases: [
      { icon: "👤", title: "Solo founders", body: "Accountant + CFO + assistant in one AI. Run the back-office solo." },
      { icon: "📈", title: "Scaling SMBs", body: "A data-driven second opinion in your decisions. Grow fast without losing the wheel." },
      { icon: "💼", title: "Finance leads", body: "Hand routine work to AI, focus on strategy." },
    ],
    pricingTitle: "Included in Pro",
    pricingBody: "Starter and Growth include basic AI queries; Pro unlocks all engines (Tax Autopilot, Death Predictor, Co-Founder).",
    faq: [
      { q: "Can the AI see my data?", a: "Only with your permission. Data stays encrypted, no personally identifiable information leaves to OpenAI/Google. KVKK and GDPR compliant." },
      { q: "How well does it handle Turkish?", a: "Gemini 2.0 supports Turkish natively, and we fine-tuned it for finance terminology and sector jargon." },
      { q: "Does Tax Autopilot replace my accountant?", a: "No — it supports them. AI prepares; your accountant approves and stays accountable." },
      { q: "Where does Voice-to-Invoice work?", a: "iOS, Android, Mac, Windows. Always-on in the mobile app; web requires microphone permission." },
    ],
    finalTitle: "Don't fear AI — use it",
    finalSub: "First 14 days free, no credit card. AI guide on every step.",
  },
  AR: {
    eyebrow: "AI · المساعد الذكي",
    h1Pre: "مدير ماليّتك بالذكاء الاصطناعي،",
    h1Highlight: "في جيبك.",
    sub: "Tax Autopilot، Death Predictor، Co-Founder Mode، Voice-to-Invoice، ومطابقة بنكية — مدعومة بـ Gemini في لوحة واحدة.",
    highlightsTitle: "اترك عمل CFO للذكاء الاصطناعي",
    highlights: [
      { icon: "🧾", title: "Tax Autopilot", body: "AI يصوغ إقرارات VAT، ومحاسبك يعتمد." },
      { icon: "💀", title: "Death Predictor", body: "يحسب 'تاريخ الموت النقدي' قبل أن يفاجئك." },
      { icon: "🤝", title: "Co-Founder Mode", body: "شريك مؤسس افتراضي تناقش معه القرارات." },
      { icon: "🎤", title: "Voice-to-Invoice", body: "قل 'أصدر فاتورة لأحمد 12,500'، يتولى AI الباقي." },
    ],
    breakdownTitle: "ماذا يوجد بالداخل؟",
    sections: [
      { title: "Tax Autopilot", body: "AI يحضّر VAT-1 وVAT-2 وإقرارات الخصم. محاسبك يعتمد بنقرة.",
        bullets: ["إعداد VAT-1 وVAT-2 آلياً", "قوالب إقرار الخصم", "إرسال مباشر إلى e-Beyanname GİB"] },
      { title: "Death Predictor", body: "يُحلّل النقد الحالي والتدفقات الداخلة والخارجة لحساب تاريخ نفاد النقد، مع توصيات.",
        bullets: ["إسقاط 30/60/90 يوماً", "عوامل الخطر وأثرها", "خطة استعادة النقد"] },
      { title: "Co-Founder Mode", body: "ناقش قراراتك مع AI: تغيير السعر، فتح خط جديد، التوظيف. رأي ثانٍ مبني على البيانات.",
        bullets: ["محاكاة سيناريوهات", "مقارنة بالقطاع", "تحليل أثر القرار على النقد"] },
      { title: "Voice-to-Invoice + المطابقة البنكية", body: "أوامر صوتية للفوترة، وAI يطابق الحركات البنكية. مطابقة بالدقائق لا الساعات.",
        bullets: ["أوامر صوتية تركية أصلية", "مطابقة آلية للحركات البنكية", "دقة مطابقة 95%+"] },
    ],
    useCasesTitle: "لمن هذه الميزة؟",
    useCases: [
      { icon: "👤", title: "المؤسسون منفردين", body: "محاسب + CFO + مساعد في AI واحد. أدر العمل وحدك." },
      { icon: "📈", title: "الشركات النامية", body: "رأي ثانٍ مبني على البيانات في قراراتك. نمُ سريعاً دون أن تفقد المقود." },
      { icon: "💼", title: "مدراء المالية", body: "اترك العمل الروتيني لـ AI وركّز على الاستراتيجية." },
    ],
    pricingTitle: "مشمولة في باقة Pro",
    pricingBody: "Starter وGrowth تتضمن استفسارات AI الأساسية، Pro يفتح كل المحركات (Tax Autopilot، Death Predictor، Co-Founder).",
    faq: [
      { q: "هل يصل AI إلى بياناتي؟", a: "فقط بإذنك. البيانات تبقى مشفرة، ولا تخرج معلومات شخصية إلى OpenAI/Google. متوافق مع KVKK وGDPR." },
      { q: "كيف يفهم AI اللغة العربية والتركية؟", a: "Gemini 2.0 يدعم اللغتين أصلياً، وقد ضبطناه على مصطلحات المالية وجارجون القطاع." },
      { q: "هل يحل Tax Autopilot محل المحاسب؟", a: "لا — بل يدعمه. AI يحضّر، والمحاسب يعتمد ويتحمل المسؤولية." },
      { q: "أين يعمل Voice-to-Invoice؟", a: "iOS، Android، Mac، Windows. دائماً في تطبيق الجوال؛ على الويب يحتاج إذن الميكروفون." },
    ],
    finalTitle: "لا تخف من AI — استخدمه",
    finalSub: "أول 14 يوماً مجاناً، بدون بطاقة. دليل AI معك في كل خطوة.",
  },
};

export const mobilContent = {
  TR: {
    eyebrow: "MOBİL · iOS + ANDROID",
    h1Pre: "İşinizi her yerde",
    h1Highlight: "yönetin.",
    sub: "Yolda fatura kesin, mobilden tahsilat takip edin, müşterilere anında ulaşın. Web'de yapabildiğiniz her şey cebinizde.",
    highlightsTitle: "Tam özellikli mobil deneyim",
    highlights: [
      { icon: "📱", title: "iOS + Android", body: "App Store ve Google Play'de native uygulamalar." },
      { icon: "📷", title: "Fiş Tarama", body: "Kamerayla fiş tarayın, AI gider olarak kaydetsin." },
      { icon: "🎤", title: "Sesle Fatura", body: "Konuşarak fatura kesin — eller dolu olduğunda bile." },
      { icon: "📡", title: "Çevrimdışı Mod", body: "İnternet yokken bile çalışır, sonra otomatik senkronize." },
    ],
    breakdownTitle: "Cebinizdeki tam panel",
    sections: [
      { title: "Push bildirimler", body: "Yeni fatura, ödeme, tahsilat, müşteri etkileşimi — anında haberdar olun.",
        bullets: ["Anlık ödeme bildirimleri", "Müşteri WhatsApp uyarıları", "Risk altındaki müşterilerde alarm"] },
      { title: "Kamera ile fiş + belge", body: "Yemek fişi, taksi makbuzu, fatura — kamerayla tarayın, AI kategorize etsin ve gider olarak kaydetsin.",
        bullets: ["OCR Türkçe + Arapça", "Otomatik kategori tahmini", "Fotoğraf cloud'da saklanır"] },
      { title: "Sesle komut", body: "'Ahmet'e 12.500 TL fatura kes' deyin, sistem hazırlasın. Yolda, mağazada, telefonda — her durumda.",
        bullets: ["Türkçe + Arapça + İngilizce sesli", "Eller serbest fatura kesimi", "Otomatik müşteri eşleştirme"] },
      { title: "Tek hesap, çoklu cihaz", body: "Web'deki veri mobile, mobildeki veri web'e — eş zamanlı senkron. Çevrimdışı çalışın, sonra senkronize olur.",
        bullets: ["Otomatik conflict resolution", "Çevrimdışı işlem kuyruğu", "1 saniyenin altında senkron"] },
    ],
    useCasesTitle: "Kimlerin işine yarar?",
    useCases: [
      { icon: "🚗", title: "Saha ekibi", body: "Yolda fatura kesin, ödeme alın, müşteri kaydedin." },
      { icon: "🏪", title: "Esnaflar", body: "Tezgahta sesle fatura, kamerayla fiş, anlık tahsilat takibi." },
      { icon: "👥", title: "Yöneticiler", body: "Cirodan churn'e — tüm metrikler cebinizde, her zaman güncel." },
    ],
    pricingTitle: "Tüm planlarda dahil",
    pricingBody: "Mobil uygulama tüm planlara ücretsiz dahildir. Plan limitleri web ile aynıdır.",
    faq: [
      { q: "Hangi telefonlarda çalışır?", a: "iOS 14+ ve Android 8+. Eski telefonlar için web sürümü her tarayıcıda çalışır." },
      { q: "Çevrimdışı modda neler yapılabilir?", a: "Fatura kesme, fiş tarama, müşteri ekleme, ödeme kaydı. İnternet bağlanınca her şey otomatik senkronize olur." },
      { q: "Mobil uygulama ekstra ücretli mi?", a: "Hayır. Tüm planlara ücretsiz dahildir. Aboneliğinizle tek hesaba bağlanır." },
      { q: "Hangi diller destekleniyor?", a: "Türkçe, İngilizce, Arapça (RTL). UI dili telefonun dilini takip eder, manuel değişiklik de mümkün." },
    ],
    finalTitle: "İşinizi cebinize alın",
    finalSub: "İlk 14 gün ücretsiz. App Store ve Google Play'den indirin.",
  },
  EN: {
    eyebrow: "MOBILE · iOS + ANDROID",
    h1Pre: "Run your business",
    h1Highlight: "anywhere.",
    sub: "Issue invoices on the road, track collections from your phone, reach customers instantly. Everything in the web app, in your pocket.",
    highlightsTitle: "Full-featured mobile, not a stripped-down version",
    highlights: [
      { icon: "📱", title: "iOS + Android", body: "Native apps on the App Store and Google Play." },
      { icon: "📷", title: "Receipt scan", body: "Snap a receipt; AI logs it as an expense." },
      { icon: "🎤", title: "Voice invoicing", body: "Talk an invoice into existence — even when your hands are full." },
      { icon: "📡", title: "Offline mode", body: "Works without internet; syncs when it returns." },
    ],
    breakdownTitle: "A full panel, in your pocket",
    sections: [
      { title: "Push notifications", body: "New invoice, payment, collection, customer interaction — find out instantly.",
        bullets: ["Real-time payment alerts", "WhatsApp interaction alerts", "At-risk customer warnings"] },
      { title: "Camera-driven receipts + docs", body: "Restaurant receipt, taxi slip, supplier invoice — snap it, AI categorises it and logs the expense.",
        bullets: ["OCR in Turkish, Arabic, English", "Auto-category prediction", "Photos stored in the cloud"] },
      { title: "Voice commands", body: "'Invoice Ahmet 12,500 TL', and the system drafts it. On the road, in a store, in a meeting.",
        bullets: ["Turkish + Arabic + English voice", "Hands-free invoicing", "Auto customer matching"] },
      { title: "One account, every device", body: "Web ↔ mobile in real-time sync. Work offline, sync later, no data loss.",
        bullets: ["Automatic conflict resolution", "Offline operation queue", "Sub-second sync when online"] },
    ],
    useCasesTitle: "Who uses it",
    useCases: [
      { icon: "🚗", title: "Field teams", body: "Issue invoices, take payments, add customers — on the move." },
      { icon: "🏪", title: "Shop owners", body: "Voice invoices at the counter, snap receipts on the way, collections live." },
      { icon: "👥", title: "Managers", body: "Revenue to churn — every metric in your pocket, always fresh." },
    ],
    pricingTitle: "Included in every plan",
    pricingBody: "The mobile app is free with every plan. Plan limits match the web.",
    faq: [
      { q: "Which phones are supported?", a: "iOS 14+ and Android 8+. Older phones can use the web app from any browser." },
      { q: "What works offline?", a: "Invoicing, receipt scanning, adding customers, payment entry. Everything syncs back the moment you reconnect." },
      { q: "Does the mobile app cost extra?", a: "No. It's included free with every plan and ties to your existing account." },
      { q: "Which languages are supported?", a: "Turkish, English, Arabic (RTL). UI language follows your phone's language, with manual override." },
    ],
    finalTitle: "Take your business with you",
    finalSub: "First 14 days free. Download on the App Store and Google Play.",
  },
  AR: {
    eyebrow: "الجوال · iOS + ANDROID",
    h1Pre: "أدر عملك",
    h1Highlight: "من أي مكان.",
    sub: "أصدر فواتير في الطريق، تابع التحصيل من جوالك، وتواصل مع العملاء فوراً. كل ما في تطبيق الويب، في جيبك.",
    highlightsTitle: "تجربة جوال كاملة، لا نسخة مصغرة",
    highlights: [
      { icon: "📱", title: "iOS + Android", body: "تطبيقات أصلية على App Store وGoogle Play." },
      { icon: "📷", title: "مسح الإيصالات", body: "صوّر إيصالاً، وAI يسجله كمصروف." },
      { icon: "🎤", title: "فوترة صوتية", body: "أنشئ فاتورة بصوتك — حتى ويداك مشغولتان." },
      { icon: "📡", title: "وضع غير متصل", body: "يعمل دون إنترنت؛ يتزامن عند العودة." },
    ],
    breakdownTitle: "لوحة كاملة في جيبك",
    sections: [
      { title: "إشعارات فورية", body: "فاتورة جديدة، دفع، تحصيل، تفاعل عميل — اعرف فوراً.",
        bullets: ["تنبيهات دفع لحظية", "تنبيهات WhatsApp", "تحذيرات للعملاء المعرضين للخطر"] },
      { title: "إيصالات ووثائق بالكاميرا", body: "إيصال مطعم، تكسي، فاتورة مورّد — صوّر، AI يصنّف ويسجل المصروف.",
        bullets: ["OCR عربي وتركي وإنجليزي", "توقع تصنيف آلي", "تخزين الصور في السحابة"] },
      { title: "أوامر صوتية", body: "'أصدر فاتورة لأحمد 12,500'، والنظام يحضّرها. في الطريق، في المتجر، في اجتماع.",
        bullets: ["أوامر صوتية بثلاث لغات", "فوترة بدون لمس", "مطابقة آلية للعملاء"] },
      { title: "حساب واحد على كل الأجهزة", body: "ويب ↔ جوال بمزامنة فورية. اعمل دون اتصال، يُزامَن لاحقاً، دون فقدان بيانات.",
        bullets: ["حل تعارضات آلي", "طابور عمليات بدون اتصال", "مزامنة بأقل من ثانية"] },
    ],
    useCasesTitle: "لمن هذه الميزة؟",
    useCases: [
      { icon: "🚗", title: "فِرق ميدانية", body: "فواتير ودفعات وتسجيل عملاء — وأنت في الطريق." },
      { icon: "🏪", title: "أصحاب المحلات", body: "فواتير صوتية على الكاونتر، إيصالات بالصورة، تحصيل لحظي." },
      { icon: "👥", title: "المدراء", body: "من الإيرادات إلى الفقد — كل المقاييس في جيبك، دائماً محدثة." },
    ],
    pricingTitle: "مشمولة في كل الباقات",
    pricingBody: "تطبيق الجوال مجاني مع كل الباقات، وحدود الباقة كحدود الويب.",
    faq: [
      { q: "ما الهواتف المدعومة؟", a: "iOS 14+ وAndroid 8+. الهواتف الأقدم تستطيع استخدام تطبيق الويب من أي متصفح." },
      { q: "ماذا يعمل دون اتصال؟", a: "إصدار الفواتير، مسح الإيصالات، إضافة العملاء، تسجيل المدفوعات. كل شيء يتزامن لحظة عودة الاتصال." },
      { q: "هل تطبيق الجوال بتكلفة إضافية؟", a: "لا. مشمول مجاناً في كل الباقات ومرتبط بحسابك الحالي." },
      { q: "ما اللغات المدعومة؟", a: "العربية (RTL) والإنجليزية والتركية. لغة الواجهة تتبع لغة الجوال مع إمكانية التغيير اليدوي." },
    ],
    finalTitle: "خذ عملك معك",
    finalSub: "أول 14 يوماً مجاناً. حمّل من App Store وGoogle Play.",
  },
};
