// ================================================================
// Sprint D-6 — Dashboard banner that surfaces the latest weekly
// performance report. Dismissible per-week (key includes ISO week
// stamp), reappears each Monday because the key changes.
// ================================================================
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { FileText, X, ArrowRight } from 'lucide-react';
import { listReports } from '@/api/v2/weeklyReport';

const LABEL = {
  title:    { tr: 'Bu haftaki performans raporun hazır',
              en: 'Your weekly performance report is ready',
              ar: 'تقرير أدائك الأسبوعي جاهز' },
  subtitle: { tr: 'AI Co-Pilot tarafından oluşturuldu',
              en: 'Generated by AI Co-Pilot',
              ar: 'تم إنشاؤه بواسطة المساعد الذكي' },
  cta:      { tr: 'Görüntüle',         en: 'View',          ar: 'عرض' },
  dismiss:  { tr: 'Bu hafta için kapat', en: 'Dismiss this week', ar: 'إخفاء هذا الأسبوع' }
};
const _ = (k, lang) => LABEL[k]?.[lang] || LABEL[k]?.tr || k;

const FRESHNESS_MS = 7 * 24 * 60 * 60 * 1000;

function isoWeekKey(date = new Date()) {
  // Monday-anchored week-of-year stamp, used as the localStorage key
  // suffix so the banner naturally reappears the following Monday.
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  const dayNum = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  const weekNo = Math.ceil((((d.getTime() - yearStart.getTime()) / 86400000) + 1) / 7);
  return `${d.getUTCFullYear()}-W${String(weekNo).padStart(2, '0')}`;
}

function dismissKey() {
  return `zyrix_weekly_banner_dismissed_${isoWeekKey()}`;
}

export default function WeeklyReportBanner({ language = 'tr' }) {
  const navigate = useNavigate();
  const [report, setReport]     = useState(null);
  const [hidden, setHidden]     = useState(false);

  useEffect(() => {
    let cancelled = false;
    // Check dismiss state first — avoid the network call if already hidden.
    try {
      if (localStorage.getItem(dismissKey()) === '1') {
        setHidden(true);
        return undefined;
      }
    } catch { /* ignore — banner just renders by default */ }

    listReports({ limit: 1 })
      .then((data) => {
        if (cancelled) return;
        const r = data?.reports?.[0];
        if (!r) return;
        const fresh = (Date.now() - new Date(r.generatedAt).getTime()) < FRESHNESS_MS;
        if (fresh) setReport(r);
      })
      .catch(() => undefined);
    return () => { cancelled = true; };
  }, []);

  const dismiss = () => {
    try { localStorage.setItem(dismissKey(), '1'); } catch { /* ignore */ }
    setHidden(true);
  };

  if (hidden || !report) return null;

  const fmtDate = (s) => {
    try {
      const d = new Date(s);
      return d.toLocaleDateString(language === 'ar' ? 'ar-EG' : language === 'tr' ? 'tr-TR' : 'en-US',
        { day: 'numeric', month: 'short' });
    } catch { return String(s).slice(0, 10); }
  };

  return (
    <div style={wrapperStyle} role="status" aria-live="polite">
      <div style={iconBox}>
        <FileText size={18} />
      </div>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={titleStyle}>{_('title', language)}</div>
        <div style={subStyle}>
          {_('subtitle', language)} · {fmtDate(report.weekStart)} — {fmtDate(report.weekEnd)}
        </div>
      </div>
      <button type="button" onClick={() => navigate(`/reports/weekly/${encodeURIComponent(report.id)}`)} style={ctaStyle}>
        {_('cta', language)}
        <ArrowRight size={13} />
      </button>
      <button type="button" onClick={dismiss} aria-label={_('dismiss', language)} style={dismissBtn}>
        <X size={14} />
      </button>
    </div>
  );
}

const wrapperStyle = {
  display: 'flex',
  alignItems: 'center',
  gap: 14,
  padding: '14px 16px',
  marginBottom: 16,
  background: 'linear-gradient(135deg, rgba(157, 78, 221, 0.06), rgba(0, 217, 255, 0.06))',
  border: '1px solid rgba(157, 78, 221, 0.18)',
  borderRadius: 14,
  boxShadow: '0 2px 12px rgba(157, 78, 221, 0.05)'
};

const iconBox = {
  flexShrink: 0,
  width: 38, height: 38,
  borderRadius: 10,
  display: 'flex', alignItems: 'center', justifyContent: 'center',
  background: 'rgba(157, 78, 221, 0.10)',
  color: '#9D4EDD'
};

const titleStyle = {
  fontSize: 13, fontWeight: 800, color: '#0F172A', letterSpacing: '-0.01em'
};

const subStyle = {
  marginTop: 2,
  fontSize: 11, color: '#64748B'
};

const ctaStyle = {
  display: 'inline-flex', alignItems: 'center', gap: 6,
  padding: '8px 16px',
  background: 'linear-gradient(135deg, #9D4EDD, #00D9FF)',
  color: '#FFFFFF',
  border: 'none',
  borderRadius: 10,
  fontSize: 12, fontWeight: 800, letterSpacing: '0.02em',
  cursor: 'pointer',
  fontFamily: 'inherit'
};

const dismissBtn = {
  flexShrink: 0,
  width: 28, height: 28,
  display: 'flex', alignItems: 'center', justifyContent: 'center',
  background: 'transparent',
  color: '#94A3B8',
  border: 'none',
  borderRadius: 6,
  cursor: 'pointer'
};
